### ISSUE TITLE
pyclean package on PyPI

### ISSUE THREAD

**Issue by bittner** [felixcarmona/pyhttp#2]
¡Hola Felix!

I know this is not the right way and the right issue tracker for contacting you about the [pyclean package](https://pypi.org/project/pyclean/) on PyPI. I don't seem to get a response from you on [my Twitter message](https://twitter.com/peterbittner/status/1106336478223876097), though. (Did you receive it?) -- Here's my question:
 
You have reserved the `pyclean` package name on PyPI. Would you mind sharing this with me and others: I'd like to build a cross-platform solution to clean up `.pyc` files and `__pycache__` folders. Please, let me know!

-----------

BTW, here are the latest implementations of `pyclean` of Debian, the commands that are distributed with the Debian python packages, authored by Piotr Ożarowski <piotr (at) debian (dot) org>:

- https://salsa.debian.org/cpython-team/python-defaults/blob/master/pyclean
- https://salsa.debian.org/cpython-team/python3-defaults/blob/master/py3clean
- https://salsa.debian.org/debian/pypy/blob/debian/debian/scripts/pypyclean

To start with, I would put them under version control on, say, GitHub as they are, and then continue from there to modernize the implementation. (I discussed this with Piotr by email, recently.)

Thanks in advance for getting back to me soon! :+1:

**Comment by felixcarmona** [comment]
Sure, send me a direct message in twitter

Best

El dc, 20 març 2019 a les 9:31 Peter Bittner <notifications@github.com> va
escriure:

**Comment by bittner** [comment]
Thanks for adding me as an owner on PyPI! :+1: 

Let's get the baby going now.

**Comment by bittner** [comment]
Thanks again, Felix, for the transition!

Here's [the story](https://mail.python.org/archives/list/distutils-sig@python.org/thread/HSUNHFMJO34DM25FE6AEOKJKKVI6CFGI/#HSUNHFMJO34DM25FE6AEOKJKKVI6CFGI) (directly off the Distutils-SIG mailing list) to encourage anyone to try it the same way, btw.
